### ISSUE TITLE
Aesthetics

### ISSUE THREAD

**Issue by Bombrrr** [SMAStudiosAU/Star-Battles#21]
maybe enhancing the aesthetics

**Comment by Inglan2** [comment]
I think we should add a color theme

**Comment by Inglan2** [comment]
Have a look here and just pick a source color: https://material-foundation.github.io/material-theme-builder/

**Comment by Inglan2** [comment]
@Bombrrr

**Comment by Inglan2** [comment]
Just added #22

**Comment by Inglan2** [comment]
Working on the sliders:
![image](https://github.com/SMAStudiosAU/Star-Battles/assets/117789688/c72ce828-45b6-4901-9621-e0fbe794a133)
Would be ncie to have a theme
